
CREATE TABLE IF NOT EXISTS `countries` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=198 ;


/*
-- Query: SELECT * FROM evo_central.countries
LIMIT 0, 1000

-- Date: 2016-05-24 14:54
*/
INSERT INTO `countries` (`id`,`name`) VALUES (1,'Afghanistan');
INSERT INTO `countries` (`id`,`name`) VALUES (2,'Albania');
INSERT INTO `countries` (`id`,`name`) VALUES (3,'Algeria');
INSERT INTO `countries` (`id`,`name`) VALUES (4,'Andorra');
INSERT INTO `countries` (`id`,`name`) VALUES (5,'Antigua and Barbuda');
INSERT INTO `countries` (`id`,`name`) VALUES (6,'Argentina');
INSERT INTO `countries` (`id`,`name`) VALUES (7,'Armenia');
INSERT INTO `countries` (`id`,`name`) VALUES (8,'Australia');
INSERT INTO `countries` (`id`,`name`) VALUES (9,'Austria');
INSERT INTO `countries` (`id`,`name`) VALUES (10,'Azerbaijan');
INSERT INTO `countries` (`id`,`name`) VALUES (11,'Bahamas');
INSERT INTO `countries` (`id`,`name`) VALUES (12,'Bahrain');
INSERT INTO `countries` (`id`,`name`) VALUES (13,'Bangladesh');
INSERT INTO `countries` (`id`,`name`) VALUES (14,'Barbados');
INSERT INTO `countries` (`id`,`name`) VALUES (15,'Belarus');
INSERT INTO `countries` (`id`,`name`) VALUES (16,'Belgium');
INSERT INTO `countries` (`id`,`name`) VALUES (17,'Belize');
INSERT INTO `countries` (`id`,`name`) VALUES (18,'Benin');
INSERT INTO `countries` (`id`,`name`) VALUES (19,'Bhutan');
INSERT INTO `countries` (`id`,`name`) VALUES (20,'Bolivia');
INSERT INTO `countries` (`id`,`name`) VALUES (21,'Bosnia and Herzegovina');
INSERT INTO `countries` (`id`,`name`) VALUES (22,'Botswana');
INSERT INTO `countries` (`id`,`name`) VALUES (23,'Brazil');
INSERT INTO `countries` (`id`,`name`) VALUES (24,'Brunei');
INSERT INTO `countries` (`id`,`name`) VALUES (25,'Bulgaria');
INSERT INTO `countries` (`id`,`name`) VALUES (26,'Burkina Faso');
INSERT INTO `countries` (`id`,`name`) VALUES (27,'Burundi');
INSERT INTO `countries` (`id`,`name`) VALUES (28,'Cambodia');
INSERT INTO `countries` (`id`,`name`) VALUES (29,'Cameroon');
INSERT INTO `countries` (`id`,`name`) VALUES (30,'Canada');
INSERT INTO `countries` (`id`,`name`) VALUES (31,'Cape Verde');
INSERT INTO `countries` (`id`,`name`) VALUES (32,'Central African Republic');
INSERT INTO `countries` (`id`,`name`) VALUES (33,'Chad');
INSERT INTO `countries` (`id`,`name`) VALUES (34,'Chile');
INSERT INTO `countries` (`id`,`name`) VALUES (35,'China');
INSERT INTO `countries` (`id`,`name`) VALUES (36,'Colombia');
INSERT INTO `countries` (`id`,`name`) VALUES (37,'Comoros');
INSERT INTO `countries` (`id`,`name`) VALUES (38,'Congo');
INSERT INTO `countries` (`id`,`name`) VALUES (39,'Costa Rica');
INSERT INTO `countries` (`id`,`name`) VALUES (40,'Cote d\'Ivoire');
INSERT INTO `countries` (`id`,`name`) VALUES (41,'Croatia');
INSERT INTO `countries` (`id`,`name`) VALUES (42,'Cuba');
INSERT INTO `countries` (`id`,`name`) VALUES (43,'Cyprus');
INSERT INTO `countries` (`id`,`name`) VALUES (44,'Czech Republic');
INSERT INTO `countries` (`id`,`name`) VALUES (45,'Denmark');
INSERT INTO `countries` (`id`,`name`) VALUES (46,'Djibouti');
INSERT INTO `countries` (`id`,`name`) VALUES (47,'Dominica');
INSERT INTO `countries` (`id`,`name`) VALUES (48,'Dominican Republic');
INSERT INTO `countries` (`id`,`name`) VALUES (49,'East Timor');
INSERT INTO `countries` (`id`,`name`) VALUES (50,'Ecuador');
INSERT INTO `countries` (`id`,`name`) VALUES (51,'Egypt');
INSERT INTO `countries` (`id`,`name`) VALUES (52,'El Salvador');
INSERT INTO `countries` (`id`,`name`) VALUES (53,'Equatorial Guinea');
INSERT INTO `countries` (`id`,`name`) VALUES (54,'Eritrea');
INSERT INTO `countries` (`id`,`name`) VALUES (55,'Estonia');
INSERT INTO `countries` (`id`,`name`) VALUES (56,'Ethiopia');
INSERT INTO `countries` (`id`,`name`) VALUES (57,'Fiji');
INSERT INTO `countries` (`id`,`name`) VALUES (58,'Finland');
INSERT INTO `countries` (`id`,`name`) VALUES (59,'France');
INSERT INTO `countries` (`id`,`name`) VALUES (60,'Gabon');
INSERT INTO `countries` (`id`,`name`) VALUES (61,'Gambia');
INSERT INTO `countries` (`id`,`name`) VALUES (62,'Georgia');
INSERT INTO `countries` (`id`,`name`) VALUES (63,'Germany');
INSERT INTO `countries` (`id`,`name`) VALUES (64,'Ghana');
INSERT INTO `countries` (`id`,`name`) VALUES (65,'Greece');
INSERT INTO `countries` (`id`,`name`) VALUES (66,'Grenada');
INSERT INTO `countries` (`id`,`name`) VALUES (67,'Guatemala');
INSERT INTO `countries` (`id`,`name`) VALUES (68,'Guinea');
INSERT INTO `countries` (`id`,`name`) VALUES (69,'Guinea-Bissau');
INSERT INTO `countries` (`id`,`name`) VALUES (70,'Guyana');
INSERT INTO `countries` (`id`,`name`) VALUES (71,'Haiti');
INSERT INTO `countries` (`id`,`name`) VALUES (72,'Honduras');
INSERT INTO `countries` (`id`,`name`) VALUES (73,'Hong Kong');
INSERT INTO `countries` (`id`,`name`) VALUES (74,'Hungary');
INSERT INTO `countries` (`id`,`name`) VALUES (75,'Iceland');
INSERT INTO `countries` (`id`,`name`) VALUES (76,'India');
INSERT INTO `countries` (`id`,`name`) VALUES (77,'Indonesia');
INSERT INTO `countries` (`id`,`name`) VALUES (78,'Iran');
INSERT INTO `countries` (`id`,`name`) VALUES (79,'Iraq');
INSERT INTO `countries` (`id`,`name`) VALUES (80,'Ireland');
INSERT INTO `countries` (`id`,`name`) VALUES (81,'Israel');
INSERT INTO `countries` (`id`,`name`) VALUES (82,'Italy');
INSERT INTO `countries` (`id`,`name`) VALUES (83,'Jamaica');
INSERT INTO `countries` (`id`,`name`) VALUES (84,'Japan');
INSERT INTO `countries` (`id`,`name`) VALUES (85,'Jordan');
INSERT INTO `countries` (`id`,`name`) VALUES (86,'Kazakhstan');
INSERT INTO `countries` (`id`,`name`) VALUES (87,'Kenya');
INSERT INTO `countries` (`id`,`name`) VALUES (88,'Kiribati');
INSERT INTO `countries` (`id`,`name`) VALUES (89,'North Korea');
INSERT INTO `countries` (`id`,`name`) VALUES (90,'South Korea');
INSERT INTO `countries` (`id`,`name`) VALUES (91,'Kuwait');
INSERT INTO `countries` (`id`,`name`) VALUES (92,'Kyrgyzstan');
INSERT INTO `countries` (`id`,`name`) VALUES (93,'Laos');
INSERT INTO `countries` (`id`,`name`) VALUES (94,'Latvia');
INSERT INTO `countries` (`id`,`name`) VALUES (95,'Lebanon');
INSERT INTO `countries` (`id`,`name`) VALUES (96,'Lesotho');
INSERT INTO `countries` (`id`,`name`) VALUES (97,'Liberia');
INSERT INTO `countries` (`id`,`name`) VALUES (98,'Libya');
INSERT INTO `countries` (`id`,`name`) VALUES (99,'Liechtenstein');
INSERT INTO `countries` (`id`,`name`) VALUES (100,'Lithuania');
INSERT INTO `countries` (`id`,`name`) VALUES (101,'Luxembourg');
INSERT INTO `countries` (`id`,`name`) VALUES (102,'Macedonia');
INSERT INTO `countries` (`id`,`name`) VALUES (103,'Madagascar');
INSERT INTO `countries` (`id`,`name`) VALUES (104,'Malawi');
INSERT INTO `countries` (`id`,`name`) VALUES (105,'Malaysia');
INSERT INTO `countries` (`id`,`name`) VALUES (106,'Maldives');
INSERT INTO `countries` (`id`,`name`) VALUES (107,'Mali');
INSERT INTO `countries` (`id`,`name`) VALUES (108,'Malta');
INSERT INTO `countries` (`id`,`name`) VALUES (109,'Marshall Islands');
INSERT INTO `countries` (`id`,`name`) VALUES (110,'Mauritania');
INSERT INTO `countries` (`id`,`name`) VALUES (111,'Mauritius');
INSERT INTO `countries` (`id`,`name`) VALUES (112,'Mexico');
INSERT INTO `countries` (`id`,`name`) VALUES (113,'Micronesia');
INSERT INTO `countries` (`id`,`name`) VALUES (114,'Moldova');
INSERT INTO `countries` (`id`,`name`) VALUES (115,'Monaco');
INSERT INTO `countries` (`id`,`name`) VALUES (116,'Mongolia');
INSERT INTO `countries` (`id`,`name`) VALUES (117,'Montenegro');
INSERT INTO `countries` (`id`,`name`) VALUES (118,'Morocco');
INSERT INTO `countries` (`id`,`name`) VALUES (119,'Mozambique');
INSERT INTO `countries` (`id`,`name`) VALUES (120,'Myanmar');
INSERT INTO `countries` (`id`,`name`) VALUES (121,'Namibia');
INSERT INTO `countries` (`id`,`name`) VALUES (122,'Nauru');
INSERT INTO `countries` (`id`,`name`) VALUES (123,'Nepal');
INSERT INTO `countries` (`id`,`name`) VALUES (124,'Netherlands');
INSERT INTO `countries` (`id`,`name`) VALUES (125,'New Zealand');
INSERT INTO `countries` (`id`,`name`) VALUES (126,'Nicaragua');
INSERT INTO `countries` (`id`,`name`) VALUES (127,'Niger');
INSERT INTO `countries` (`id`,`name`) VALUES (128,'Nigeria');
INSERT INTO `countries` (`id`,`name`) VALUES (129,'Norway');
INSERT INTO `countries` (`id`,`name`) VALUES (130,'Oman');
INSERT INTO `countries` (`id`,`name`) VALUES (131,'Pakistan');
INSERT INTO `countries` (`id`,`name`) VALUES (132,'Palau');
INSERT INTO `countries` (`id`,`name`) VALUES (133,'Panama');
INSERT INTO `countries` (`id`,`name`) VALUES (134,'Papua New Guinea');
INSERT INTO `countries` (`id`,`name`) VALUES (135,'Paraguay');
INSERT INTO `countries` (`id`,`name`) VALUES (136,'Peru');
INSERT INTO `countries` (`id`,`name`) VALUES (137,'Philippines');
INSERT INTO `countries` (`id`,`name`) VALUES (138,'Poland');
INSERT INTO `countries` (`id`,`name`) VALUES (139,'Portugal');
INSERT INTO `countries` (`id`,`name`) VALUES (140,'Puerto Rico');
INSERT INTO `countries` (`id`,`name`) VALUES (141,'Qatar');
INSERT INTO `countries` (`id`,`name`) VALUES (142,'Romania');
INSERT INTO `countries` (`id`,`name`) VALUES (143,'Russia');
INSERT INTO `countries` (`id`,`name`) VALUES (144,'Rwanda');
INSERT INTO `countries` (`id`,`name`) VALUES (145,'Saint Kitts and Nevis');
INSERT INTO `countries` (`id`,`name`) VALUES (146,'Saint Lucia');
INSERT INTO `countries` (`id`,`name`) VALUES (147,'Saint Vincent and the Grenadines');
INSERT INTO `countries` (`id`,`name`) VALUES (148,'Samoa');
INSERT INTO `countries` (`id`,`name`) VALUES (149,'San Marino');
INSERT INTO `countries` (`id`,`name`) VALUES (150,'Sao Tome and Principe');
INSERT INTO `countries` (`id`,`name`) VALUES (151,'Saudi Arabia');
INSERT INTO `countries` (`id`,`name`) VALUES (152,'Senegal');
INSERT INTO `countries` (`id`,`name`) VALUES (153,'Serbia and Montenegro');
INSERT INTO `countries` (`id`,`name`) VALUES (154,'Seychelles');
INSERT INTO `countries` (`id`,`name`) VALUES (155,'Sierra Leone');
INSERT INTO `countries` (`id`,`name`) VALUES (156,'Singapore');
INSERT INTO `countries` (`id`,`name`) VALUES (157,'Slovakia');
INSERT INTO `countries` (`id`,`name`) VALUES (158,'Slovenia');
INSERT INTO `countries` (`id`,`name`) VALUES (159,'Solomon Islands');
INSERT INTO `countries` (`id`,`name`) VALUES (160,'Somalia');
INSERT INTO `countries` (`id`,`name`) VALUES (161,'South Africa');
INSERT INTO `countries` (`id`,`name`) VALUES (162,'Spain');
INSERT INTO `countries` (`id`,`name`) VALUES (163,'Sri Lanka');
INSERT INTO `countries` (`id`,`name`) VALUES (164,'Sudan');
INSERT INTO `countries` (`id`,`name`) VALUES (165,'Suriname');
INSERT INTO `countries` (`id`,`name`) VALUES (166,'Swaziland');
INSERT INTO `countries` (`id`,`name`) VALUES (167,'Sweden');
INSERT INTO `countries` (`id`,`name`) VALUES (168,'Switzerland');
INSERT INTO `countries` (`id`,`name`) VALUES (169,'Syria');
INSERT INTO `countries` (`id`,`name`) VALUES (170,'Taiwan');
INSERT INTO `countries` (`id`,`name`) VALUES (171,'Tajikistan');
INSERT INTO `countries` (`id`,`name`) VALUES (172,'Tanzania');
INSERT INTO `countries` (`id`,`name`) VALUES (173,'Thailand');
INSERT INTO `countries` (`id`,`name`) VALUES (174,'Togo');
INSERT INTO `countries` (`id`,`name`) VALUES (175,'Tonga');
INSERT INTO `countries` (`id`,`name`) VALUES (176,'Trinidad and Tobago');
INSERT INTO `countries` (`id`,`name`) VALUES (177,'Tunisia');
INSERT INTO `countries` (`id`,`name`) VALUES (178,'Turkey');
INSERT INTO `countries` (`id`,`name`) VALUES (179,'Turkmenistan');
INSERT INTO `countries` (`id`,`name`) VALUES (180,'Tuvalu');
INSERT INTO `countries` (`id`,`name`) VALUES (181,'Uganda');
INSERT INTO `countries` (`id`,`name`) VALUES (182,'Ukraine');
INSERT INTO `countries` (`id`,`name`) VALUES (183,'United Arab Emirates');
INSERT INTO `countries` (`id`,`name`) VALUES (184,'United Kingdom');
INSERT INTO `countries` (`id`,`name`) VALUES (185,'United States');
INSERT INTO `countries` (`id`,`name`) VALUES (186,'Uruguay');
INSERT INTO `countries` (`id`,`name`) VALUES (187,'Uzbekistan');
INSERT INTO `countries` (`id`,`name`) VALUES (188,'Vanuatu');
INSERT INTO `countries` (`id`,`name`) VALUES (189,'Vatican City');
INSERT INTO `countries` (`id`,`name`) VALUES (190,'Venezuela');
INSERT INTO `countries` (`id`,`name`) VALUES (191,'Vietnam');
INSERT INTO `countries` (`id`,`name`) VALUES (192,'Yemen');
INSERT INTO `countries` (`id`,`name`) VALUES (193,'Zambia');
INSERT INTO `countries` (`id`,`name`) VALUES (194,'Zimbabwe');

